### ISSUE TITLE
Add option to disable to resize the rectangle

### ISSUE THREAD

**Issue by ustroetz** [heyman/leaflet-areaselect#7]
This is a feature request. It would be nice to add a option to disable the ability to re-size the rectangle.

**Comment by valerio-bozzolan** [comment]
As workaround you can just do this in your CSS:

```css
.leaflet-areaselect-handle {
    display: none;
}
```

Maybe we can add this in the README, instead of adding an option in the code.
